site_name: SPNATI Docs
site_url: https://spnati.net/docs/
use_directory_urls: false
nav:
    - 'Getting Started':
        - 'Start Here!': 'start_guides/intro.md'
        - 'Pose Organization': 'userdocs/pose_organization.md'
    - 'References':
        - 'Dialogue Formatting': 'dialogue/formatting.md'
        - 'Conditions': 'dialogue/conditions.md'
        - 'Variables': 'dialogue/variables.md'
        - 'Tagging': 'dialogue/tags.md'
        - 'Backgrounds': 'dialogue/backgrounds.md'
        - 'Collectibles': 'extras/collectibles.md'
        - 'KKL Alpha Transparency': 'kkl/alpha_transparency.md'
        - 'KKL Remote Control Protocol': 'kkl/kkl_local_protocol.md'
    - 'Advanced':
        - 'Creating Manual Merge Requests': 'advanced/githubmerge.md'
        - 'Adding and Editing Documentation': 'advanced/writingguides.md'
    - 'Policy':
        - 'Testing and Sponsorship': 'policy/testing_sponsorship.md'

markdown_extensions:
    - admonition