site_name: SPNATI Docs
site_url: https://spnati.net/docs/
use_directory_urls: false
nav:
    - 'The Basics':
        - 'Character Development Guide': 'basics/chardevguide.md'
        - 'Using Github Desktop': 'basics/githubdesktop.md'
        - 'How to Play the Offline Version': 'basics/playingoffline.md'
        - 'New Dev FAQ': 'basics/newdevfaq.md'
    - 'Dialogue':
        - 'Conditions': 'dialogue/conditions.md'
        - 'Variables': 'dialogue/variables.md'
        - 'Tagging': 'dialogue/tags.md'
        - 'Backgrounds': 'dialogue/backgrounds.md'
        - 'Dialogue Formatting': 'dialogue/formatting.md'
        - 'Dialogue Operations': 'dialogue/operations.md'
    - 'Art':
        - 'Intro to Kisekae': 'kkl/kisekae_guide.md'
        - 'KKL Alpha Transparency': 'kkl/alpha_transparency.md'
        - 'KKL Remote Control Protocol': 'kkl/kkl_local_protocol.md'
    - 'Advanced':
        - 'Collectibles': 'advanced/collectibles.md'
        - 'Character Editor Recipes': 'advanced/recipes.md'
        - 'Creating Manual Merge Requests': 'advanced/githubmerge.md'
        - 'Mac OS Dev Guide': 'advanced/macguide.md'
        - 'How to Collaborate on Character Creation': 'advanced/collaborativeworkflow.md'
        - 'Adding and Editing Documentation': 'advanced/writingguides.md'
    - 'Policy':
        - 'Rules': 'policy/rules.md'
        - 'Testing': 'policy/testing.md'
        - 'Sponsorship': 'policy/sponsorship.md'
        - 'Adoption and Reworks': 'policy/reworks.md'
    - 'User Submitted':
        - "Spnati_edit's Youtube Channel": 'https://www.youtube.com/channel/UC3lqu7IuyolqxJAcTLAFpuw'
        - 'Linux Development Guide': 'userdocs/linuxguide.md'
        - 'Overlaying Patterns on Clothes with Pipelines' : 'userdocs/overlaying_patterns.md'
        - 'Playing Offline on Phone through LAN' : 'userdocs/LAN_guide.md'
        - "SPNatI Collaborative Writing Guide": 'https://docs.google.com/document/d/1kLkq-4dPo8CfXoiJ37SIqkifReGNGsAYqaxm-gXQhQY'


markdown_extensions:
    - admonition

extra_css:
    - css/extra.css

theme:
  name: null
  custom_dir: 'cinder'
